### ISSUE TITLE
[additional] getter, setter 를 지양하자

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#15]
## 연관 챕터
#4

## 조사 내용
책을 읽다가 문득 `getter 와 setter 는 왜 필요할까?` 라는 의문이 들었습니다.
당연히 모두들 알고 계시겠지만, 변수를 캡슐화하기 위해서겠죠?

getter, setter 메서드를 만들어서 변수를 private 으로 보호한다. 는 학부시절부터 너무 당연하게 배워왔고 항상 변수는 private 으로 두고, set메서드로 변경했었습니다.
그런데 이번에 코틀린을 배우면서 신기했던 점이, 코틀린에선 set 메서드를 쓰지 않는다는 점이었습니다.
코틀린은 언어 자체에서 getter, setter 를 지원하기 때문에 모든 변수가 기본적으로 private 이고, 코틀린에서의 private 여부에 따라 getter, setter 가 지원됩니다.

```
var name: String  // 클래스 외부에서 getter, setter 사용
val name: String  // 클래스 외부에서 getter 사용
private var name: String  // 클래스 내부에서 getter, setter 사용
private val name: String  // 클래스 내부에서 getter 사용

// 자바 코드로 변환하면 4가지 경우 모두 private String name 으로 되어있음
```
특이한 점은 setter 를 사용할 때 setName() 이 아닌, name = "asd" 처럼 변수를 수정하게끔 하는 것이었습니다.
굳이 내부적으로 getter, setter 를 만들어놓고 결국에 사용자는 public 변수처럼 쓰게 되더라구요
```
name = "asd"  // 자바의 setName("asd")
```

무분별하게 단순한 getter, setter 를 만들어 쓰는건 그냥 그 변수를 public 으로 쓰는거랑 다름이 없겠구나 라는 생각이 들었습니다. (롬복의 getter, setter 자동 생성 기능은 정말 쓸데없는 기능이었다?!)
그래서 코틀린에서도 setter 메서드에 큰 의미를 두지 않게 의도한 것 같구요.(변수를 직접 조작하는 것과 같은 경험을 하게되니..)

이것저것 생각을 해보고, 글도 찾아 보았는데 getter, setter 는 잘못 사용되던 관습이었고, 행위를 예측할 수 있는 메서드를 사용해 get, set 하는 걸 지향해야 한다! 라는 결론을 내렸습니다.

getter, setter 를 지양하자 라는 내용으로 검색을 해보니 좋은 글들이 많더라구요.
getter 를 지양해야 하는 이유 : https://msmk530.tistory.com/72
getter, setter 가 의미가 있나? : https://devstu.co.kr/howto/question/20 (이카루스님의 답변이 와닿네요)

**Comment by wooyounggggg** [comment]
getter와 setter의 무분별한 사용은 캡슐화를 약하게 만들고, 그 결과로 객체지향적 설계가 무너지는 결과를 초래할 수 있을 것 같습니다.

getter나 setter가 프레임워크 수준에서 꼭 필요한 것이 아니라면, 굳이 필요하지 않다고 생각되기도 하네요!

만약 코드에서 getter, setter가 필요한 경우가 있다면 책임 분리가 잘 되지 않은 것이 아닐까 생각합니다.
