### ISSUE TITLE
[question] 설계 품질과 "트레이드 오프"

### ISSUE THREAD

**Issue by ngwoon** [caffeine-library/objects#17]
## 질문

챕터 4의 제목은 "설계 품질과 트레이드 오프" 입니다. 이 챕터를 읽고, 핵심 내용이 아래와 같다고 생각했습니다.
> 설계 품질을 결정하는 요소로 캡슐화와 결합도, 응집도가 있고, 낮은 결합도와 높은 응집도를 갖도록 설계해야 진정한 객체지향 설계라고 볼 수 있다.
>

이렇게 요약을 해보고 나니, 챕터 제목에 등장하는 "설계 품질" 이라는 단어는 왜 등장했는지 이해가 됐으나, "트레이드 오프" 라는 단어는 굳이 왜 넣었는지 의아했습니다.

제가 이에 대해 나름 생각해본 결과는 다음과 같습니다.
> 데이터 중심적으로 설계를 하면 직관적이고 프로그래밍이 쉽지만, 유지보수적인 측면에서 매우 좋지 않기 때문에 캡슐화와 결합도, 응집도를 고려해야 한다. 이처럼 캡슐화를 제대로 적용하고 낮은 결합도, 높은 응집도를 갖도록 설계하는건 개발자가 설계에 들여야하는 시간, 노력과 트레이드 오프 관계이다.
>

위와 같은 맥락에서 챕터 제목에 트레이드 오프 라는 단어가 들어간 것으로 추측이 되는데, 다른 분들은 책을 읽으면서 트레이드 오프와 관련한 내용을 캐치하신 부분이 있는지 궁금합니다.

## 연관 챕터

#13 

@caffeine-library/readers-objects

**Comment by wooyounggggg** [comment]
비슷한 맥락으로, 일전에 한 시니어 개발자분께서 아래와 같은 말씀을 해주신 적이 있었습니다.

> 프로그램을 설계할 때, 레이어가 하나 더 들어서게 되면 중복을 줄이고 변화에 유연하게 대응할 수 있는 효과가 있지만
> 그만큼 더 많은 공수가 들어가기 때문에, 주어진 비즈니스적 상황을 고려해서 레이어를 나누어야 한다.

마찬가지로 객체를 책임을 분할하고 각각을 캡슐화해서 변화에 유연하게 설계하는 것은 넓은 관점에서 위의 Layer의 이야기에 포함되는 주제가 아닐까 생각되는 부분이 있습니다.
