### ISSUE TITLE
[question] 도메인 모델에 대한 이해

### ISSUE THREAD

**Issue by emiling** [caffeine-library/objects#18]
## 질문

질문이 다소 추상적인 것 같긴 하지만, "도메인 모델"이 무엇인지 개념을 확립하면 좋을 것 같아 만들었습니다.

저 스스로 생각해보니 이 `도메인`에 대한 명확한 이해 없이 단어를 사용하고 있는 것 같기도 하고
여러분이 이해하고 있는 도메인 모델에 대해 의견을 듣고 싶기도 합니다.

### 관련 키워드
- Rich vs Anemic Domain model
  - https://martinfowler.com/bliki/AnemicDomainModel.html
  - https://www.amido.com/blog/anaemic-domain-model-vs-rich-domain-model

## 연관 챕터

https://github.com/caffeine-library/objects/issues/13

@caffeine-library/readers-objects

**Comment by JasonYoo1995** [comment]
> 참고한 프로젝트 : https://github.com/JasonYoo1995/spring-sample-project
> 참고한 링크 : https://stackoverflow.com/a/29914384

- Anemic Domain Model : 비즈니스 로직을 '엔티티 클래스 외부'에 넣는 방법 ( ex : '서비스 계층' 등)
- Rich Domain Model : 비즈니스 로직을 '엔티티 클래스 내부'에 넣는 방법

- Anemic Domain Model 의 장점
  - 서비스 계층만 보고도 전체 비즈니스 로직을 파악할 수 있다
- Rich Domain Model 의 장점
  - 재사용성 : 여러 메서드에서 똑같은 로직을 다시 작성할 필요 없음
  - 특정 엔티티의 비즈니스 로직에 **변경**이 생겼을 때, 오직 "한 군데"만 바꾸면 된다. (= 변경에 안정적, 변경이 편리)

---
@caffeine-library/readers-objects
