### ISSUE TITLE
[keyword] 5장 - 책임 할당하기

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#20]
## 주제

`5장 - 책임 할당하기`을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터
#19

**Comment by binchoo** [comment]
## 책임 주도 설계

### 행동을 먼저 정한다

- **객체의 존재 의의**: 협력에서 수행하는 책임이 있다.
  -  책임은 클라이언트 객체 관점에서 해당 객체가 제공하는 행동
- **데이터를 먼저 결정하기**: 데이터는 행동을 보조하기 위한 재료일 뿐이다. 객체의 데이터를 먼저 결정하게 되면 내부 구현을 외부로 쉽게 노출하게 되고 높은 응집도와 낮은 결합도의 설계로 이어진다.
- **행동을 먼저 결정하기**: 협력 안에서 클라이언트의 요구사항을 발견하고, 이 요구사항을 충족할 객체를 찾아 책임을 할당한다. 

### 협력 속에서 책임을 찾는다

- **협력에 적합한 책임**: 협력 객체에 메시지를 전송하는 **클라이언트가 편해야 한다**. 클라이언트의 의도가 담긴 형태로 책임이 발견되어야 하고, 객체에게 할당되어야 한다. 
- **메시지를 먼저 결정하기**: 클라이언트의 의도는 메시지에 담긴다. 메시지를 먼저 결정하게 방식으로, 협력 객체는 클라이언트가 분부한 책임을 제공하되 내부 구현을 노출하지 않는다. 클라이언트가 편하려면 협력 객체에 대해 자세히 알 필요가 없어야 한다.

**Comment by binchoo** [comment]
## GRASP 원칙

GRASP: 일반적인 책임 할당을 위한 소프트웨어 패턴

### 도메인 개념 활용하기

- **도메인을 코드에 투영**: 도메인 모델에서 식별한 개념을 책임 할당의 대상으로 사용하면 코드에 도메인을 투영하기 쉬워진다.
- **도메인 모델은 구현과 동떨어지지 않는다**: 도메인 모델은 구현의 기반이 되고, 반대로 코딩 과정에서 얻은 통찰이 도메인 모델을 수정하기도 한다. 현실 세계를 완벽하게 모델링 하는 것 보다 구현에 실용적이고 유용한 모델이 더 낫다.

### 정보 전문가 패턴

책임을 수행할 때 필요한 정보를 잘 알고 있는 객체에게 그 책임을 할당한다.

- **정보 != 데이터**: 정보를 알고 있는 것과 저장하는 것은 다르다. 객체는 책임 수행을 위한 구현을 알고 있어나, 책임을 대신 수행해 줄 다른 협력 객체를 알고 있기도 한다. 정보 전문가란 책임과 관련된 데이터를 저장하고 있음을 의미하지 않는다.

### 높은 응집도와 낮은 결합도

객체들이 협력을 설계하는데 다양한 대안들이 도출될 수 있다. 어떤 설계를 택할지 트레이드 오프를 따질 때 응집도와 결합도를 기준으로 삼을 수 있다.

- 도메인 모델에서 `Movie` 가 `DiscountCondition`을 속성으로 갖고 있기 때문에, `Screening`이 `DiscountCondition`을 취해 할인여부를 판단하는 것 보단, `Movie`가 `DiscountCondition`과 협력하는 것이 결합도가 낮고 응집도도 높다.
- 클래스 응집도 판단
  - 클래스가 하나 이상의 이유로 변경된다면 응집도가 낮다. 변경의 이유를 기준으로 클래스를 분화하자.
  - 인스턴스 초기화 시 경우에 따라 서로 다른 속성만을 초기화하면 응집도가 낮다. 초기화 되는 속성 그룹을 기준으로 클래스를 분화하자.
  - 메서드 집단별로 서로 다른 속성 집단만 이용한다면 응집도가 낮다. 집단 별로 클래스를 분리하자.

### 창조자 패턴

어떤 객체를 생성하는 책임은 이미 결합된 객체에게 할당하면 좋다. A를 생성하는 책임은 아래 조건을 잘 만족하는 B에게 할당하자.

- B가 A를 포함하거나 참조한다.
- B가 A를 기록한다.
- B가 A를 긴밀하게 사용한다.
- B가 A 객체를 초기화하는데 필요한 데이터를 갖고 있다.

### 다형성 패턴

조건문을 이용하기 보단 객체의 타입에 따라 구현의 여러가지 대안을 제공해야 한다.

### 변경 보호 패턴

변화가 예상되는 지점엔 안정적인 인터페이스를 두어 캡슐화한다.

**Comment by emiling** [comment]
### 다형성으로 생각해보는 추상 클래스와 인터페이스의 차이 (p.156)

동일한 "책임"을 수행한다는 것은 동일한 "역할"을 수행하는 것을 의미한다
-  책에서 `Movie` 입장에서는 `SequenceCondition`을 사용하든, `PeriodCondition`을 사용하든 중요하지 않음 
- 서비스 계층에서 어떤 '상품'을 가져오는 로직(`selectProduct`)이 있다고 가정할 때, 
     `selectProduct` 라는 함수가 `ticket` 테이블을 참조하여 가져오는지 `book` 테이블을 참조해서 가져오는지 몰라도 됨

이러한 몰라도 되는 부분 (실질적인 구현파트)은 감추도록 해야한다 (캡슐화)
좋은 설계는 호출하는 객체가 구체적인 클래스는 알지 못하게 감추고, 오로지 역할에 대해서만 노출하여 결합되도록 의존성을 제한한다.

#### 정리

- 추상클래스 : 역할을 대체할 클래스들 사이에 "구현을 공유" 해야할 필요가 있다면 
- 인터페이스 : 역할을 대체할 클래스들 사이에 "구현을 공유" 해야할 필요가 없다면

> 여기서 얘기하는 "구현을 공유" 하는 예시가 어떤 것이 있을지 한 번 얘기해보면 좋을 것 같습니다
> (혹은 추상클래스를 사용하여 "역할" 을 표현했던 경험)

**Comment by leejaeseung** [comment]
저도 이번에 추상클래스와 인터페이스에 대해 생각을 좀 해보았는데, 말씀하신 것처럼 **구현을 공유**하는 점에서의 차이점이 있지만 자바8을 비롯해 많은 최신 언어에선 인터페이스도 디폴트 메서드를 지원하고 있습니다. 즉, 인터페이스도 구현을 공유할 수 있도록 되고 있죠. (심지어 코틀린에선 인터페이스도 변수를 가질 수 있습니다)

**구현을 공유한다** 라는 관점에서 보면 추상클래스와 인터페이스의 차이가 점점 모호해져 가는 것 같은데, 그래서 저는 둘의 차이가 단일 상속, 다중 상속의 차이라고 생각하고 있습니다.

추상클래스는 단일 상속을 강제함으로써 부모 클래스에 대한 의존성을 더 명시적으로 나타낼 수 있고, 인터페이스는 다중 상속이 가능하게 되면서 유연함을 강조하고 있는게 아닐까 싶네요.
저도 아직까지 애매하게 생각하고 있는 부분이라 의견 나눠보면 좋을 듯 합니다!
