### ISSUE TITLE
[additional] 바람직한 공통화 - 공통 모듈

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#21]
## 연관 챕터
챕터와 별개의 경험입니다.

## 조사 내용
이전 프로젝트에서 멀티 모듈을 사용하며 공통화에 대해 다시 한번 생각하게된 경험이 있어 공유 드리려 합니다.
이 경험 이전까지 공통화에 대해, 언제든 중복되는 코드는 하나로 합쳐야 무조건 좋다! 라는 고정관념이 있었는데 더 넓은 시각을 갖게 된 것 같네요 ㅎㅎ

일단 프로젝트는 다음과 같이 4 가지의 모듈로 구성되었습니다.
- common : app, pubsub 모듈에서 공통으로 사용되는 모듈
- domain : entity 와 관련된 로직만을 모아두는 모듈
- app : 독립적으로 실행되는 모듈 1
- pubsub : 독립적으로 실행되는 모듈 2

프로젝트를 진행하다보니 어떤 SomeEntity 에 대한 조작(create, update, find)을 하는 Service 가 생겼습니다.
```
class SomeEntityService {
    createSomeEntity() {}
    updateSomeEntity() {}
    findSomeEntity() {}
}
```
그런데 app 과 pubsub 모듈은 같은 domain 을 공유했기 때문에 SomeEntity 에 대해 비슷한 작업을 하는 Service 가 필요했습니다.
(ex app 에서 SomeEntity 를 create 하면 pubsub 에서 SomeEntity 를 find 해 update 하는 등의 작업)
굳이 app, pubsub 에 `SomeEntityService` 를 각각 두지 말고 common 에 두고 공통으로 관리하면 어떨까? 라는 생각이 들었습니다.
(오로지 코드가 분리되는게 싫어서.. 지금 생각하면 아찔하네요)

결국 아래 글을 읽고 문제점이 많다는 걸 느꼈고, 공통화에 대해 다시 생각하게 된 것 같습니다.
(너무 좋은 글이고, 상황이 제 프로젝트랑 거의 동일하더군요)
https://techblog.woowahan.com/2637/

프로젝트가 진행될수록 app, pubsub 에 나눠진 `SomeEntityService` 의 기능들이 app, pubsub 마다 조금씩 많이 달라져서 이걸 공통으로 모으려 했으면 `SomeEntityService` 가 쓸데없이 거대해지지 않았을까 생각이 드네요..

**Comment by binchoo** [comment]
글 잘 읽었습니다!

그래이들 멀티 모듈 구성에서 

테스트 유틸리티 클래스를 공통적으로 의존해야 할 때 

**testFixtures** 라는 소스 세트를 담당 모듈에서 정의하여 외부에 노출해 줄 수 있는데요.

이 방식도 공통의 테스트 유틸리티 모듈을 생성하지 않도록 해 주는 기법입니다.

https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures
https://vkuzel.com/shared-test-sources-in-gradle-multi-module-project

**Comment by emiling** [comment]
### Mono Repo VS Poly Repo
- https://monorepo.tools/
- https://tech.buzzvil.com/handbook/multirepo-vs-monorepo/

**Comment by emiling** [comment]
최근에 읽고 있는 TDD 서적에서 **테스트 간 테스트 픽스처 재사용**  관련하여 언급한 부분이 있는데
저번주에 얘기한 게 생각나서 짧게 공유하려고 합니다.


### 테스트 생성자에서 초기화 코드 호출

```C#
    public class CustomerTests
    {
        private readonly Store _store;
        private readonly Customer _sut;

        public CustomerTests()
        {
            _store = new Store();
            _store.AddInventory(Product.Shampoo, 10);
            _sut = new Customer();
        }

        [Fact]
        public void Purchase_succeeds_when_enough_inventory()
        {
            bool success = _sut.Purchase(_store, Product.Shampoo, 5);

            Assert.True(success);
            Assert.Equal(5, _store.GetInventory(Product.Shampoo));
        }

        [Fact]
        public void Purchase_fails_when_not_enough_inventory()
        {
            bool success = _sut.Purchase(_store, Product.Shampoo, 15);

            Assert.False(success);
            Assert.Equal(10, _store.GetInventory(Product.Shampoo));
        }
    }
```

- 테스트 간 결합도가 높아진다
  - 여기서의 결합도는 테스트 준비로직을 수정하면 클래스의 모든 테스트에 영향이 간다는 것
  - 테스트를 수정해도 다른 테스트에 영향을 주기 때문에 특정 테스트가 실패할 수 있음 (테스트 격리에 실패)
- 테스트 가독성이 떨어진다
  - 테스트 메서드가 무엇을 하는지 이해하려면 클래스의 다른 부분도 같이 봐야함 

따라서 이러한 로직을 개선하려면 테스트 클래스에 **비공개 팩토리 메서드**를 두는 것을 제안하고 있습니다.


```C#
public class CustomerTests
    {
        [Fact]
        public void Purchase_succeeds_when_enough_inventory()
        {
            Store store = CreateStoreWithInventory(Product.Shampoo, 10);
            Customer sut = CreateCustomer();

            bool success = sut.Purchase(store, Product.Shampoo, 5);

            Assert.True(success);
            Assert.Equal(5, store.GetInventory(Product.Shampoo));
        }

        [Fact]
        public void Purchase_fails_when_not_enough_inventory()
        {
            Store store = CreateStoreWithInventory(Product.Shampoo, 10);
            Customer sut = CreateCustomer();

            bool success = sut.Purchase(store, Product.Shampoo, 15);

            Assert.False(success);
            Assert.Equal(10, store.GetInventory(Product.Shampoo));
        }

        private Store CreateStoreWithInventory(Product product, int quantity)
        {
            Store store = new Store();
            store.AddInventory(product, quantity);
            return store;
        }

        private static Customer CreateCustomer()
        {
            return new Customer();
        }
    }
```

- 공통 초기화 코드를 비공개 팩토리로 추출하면서 테스트 코드를 간결화 했고, 테스트 진행 상황에 대한 전체 맥락 유지
- 비공개 팩토리 메서드를 일반화하게 되면서 테스트가 결합되지 않도록 함
- 읽기가 쉽고 재사용이 간결해짐, 재사용성이 늘어남
- 그러나 모든 테스트에 또는 거의 대부분의 테스트에 사용되는 경우 생상자에 픽스처를 인스턴스화할 수도 있다.
  -  ex. 통합테스트에서 데이터베이스 연결 등이 필요한 사례
- 이런 경우 기초 클래스를 둬서 개별 테스트 클래스가 아니라 클래스 생성자에서 데이터베이스 연결을 초기화 하는 것이 합리적이다.

**Comment by binchoo** [comment]
Spring smit contain c
