### ISSUE TITLE
[keyword] 6장. 메시지와 인터페이스

### ISSUE THREAD

**Issue by binchoo** [caffeine-library/objects#23]
## 주제

'6장 - 메시지와 인터페이스'를 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#22 

@caffeine-library/readers-objects

**Comment by leejaeseung** [comment]
# 부수효과를 없애자!

책의 예제 중 **명령 메소드**인 reschedule 메소드가 있는데, 부수효과 때문에 안정적인 메소드가 아니라고 생각하여 부수효과가 끼칠 영향과 해결방안을 정리해 보았습니다.

reschedule 메소드는 event 객체의 스케줄을 바꾸고 아무것도 반환하지 않는 명령 메소드입니다.
간단한 코드의 경우, reschedule 메소드를 보고 해당 event 객체의 스케줄이 변경된 걸 확인할 수 있겠지만 다소 복잡한 코드가 될수록 개발자에게 난해하게 다가올 수 있습니다.

가령, 이전 스케줄과 바뀐 스케줄의 차이를 구하는 코드가 reschedule 앞 뒤에 있다고 하면
```
int prevSchedule = event.schedule

//... 엄청 많은 코드들...
event.reschedule("4월 23일")
//... 엄청 많은 코드들...

int nowSchedule = event.schedule

System.out.println(prevSchedule - nowSchedule)
```
위 코드에서 많은 코드들에 가려진 reschedule 메소드를 보지 못했다면 이 코드를 처음 본 개발자는 prevSchedule 과 nowSchedule 이 같은 값을 가진다고 생각할 수 있습니다.
위 코드에선 많은 코드들에 가려졌다고만 표현되었는데, 최악의 경우 다른 메소드들에서 reschedule 메소드가 중구난방으로 호출되어 예상치 못한 값이 되어버릴 수도 있겠죠...

이 문제의 원인은 event 객체가 자기자신을 변화시키며(부수효과를 일으키며) 돌아다니기 때문입니다.
객체가 변화하면서 여러 메소드를 떠돌아다니나 보면, 어느 순간엔 개발자가 의도치 않은 상태인채로 동작을 수행할 수도 있습니다. (위 코드에서 의도치 않은 리스케줄링) 따라서 객체를 사용하는 시점엔 개발자가 의도한 상태인 객체만을 사용해야 합니다.

```
public Event reschedule(schedule) {
    return new Event(schedule)
}
```
위 코드처럼 리스케줄링된 새로운 객체를 반환하고, 사용하는 쪽에선 변화 전/후 객체를 나눠서 사용하는게 코드의 안정성 측면에서 바람직하다고 생각합니다.

적고나니 이전 JPA 트랜잭션 이슈에서와 비슷한 내용인 것 같네요.. 아무래도 이전 프로젝트에서 객체의 불변성을 강조해 개발하다보니 reschedule 같은 메소드만 보면 불안해지는 것 같습니다..ㅋㅋ

**Comment by binchoo** [comment]
# 6장 내용 정리
객체의 인터페이스 품질을 높이는 방법에 대한 챕터입니다.

- 객체지향에서 객체 간 협력은 메시지 전송을 통해 이뤄진다.
- 메시지 전송 객체는 수신 객체가 적절한 서비스를 제공할 것이라 믿는다. (검증 활동이 필요한 이유)
- 메시지 수신 객체는 런타임에 적절한 메서드로 메시지에 반응한다.

## Notations

- **메시지 전송자**
- **메시지 수신자**
- **퍼블릭 인터페이스** = 객체가 외부로 공개하는 오퍼레이션 집합
- **오퍼레이션** = 퍼블릭 인터페이스에 포함된 메시지. 객체가 호출될 수 있는 변환이나 정의에 관한 명세. 오퍼레이션은 추상적이다.
- **메시지** = {오퍼레이션명, 인자}
  `isSatisfiedBy(screening)` 
- **메시지 전송** = {메시지, 메시지 수신자}
  `condition.isSatisfiedBy(screening)`
- **메서드** = 메시지 전송으로 오퍼레이션이 호출되었을 때 반응하는 실제 함수/프로시저. 메서드는 오퍼레이션을 구현한 것이다.
  ```java
  @Override
  boolean isSatisfiedBy(Screening screening) { 
    //오퍼레이션 구현;
  }
  ```
- 시그니처 = {오퍼레이션이나 메서드의 이름, 인자, (반환값)}
   `boolean isSatisfiedBy(Screeening screening)`

## 인터페이스와 설계 품질
∝ 최소한의 인터페이스
∝ 추상적인 인터페이스
∝ 협력 객체의 변화에 노출되지 않기
∝ 객체의 상태를 묻지 않고, 행동을 요청하기
∝ 오퍼레이션명에 의도를 드러내기
∝ 명령과 쿼리를 의식적으로 구분하여 사용하기

### 책임 주도 설계의 이점
책임 주도 설계는 따르면 최소한의, 추상적인 인터페이스를 구성할 수 있게 해줍니다.
- 클라이언트는 다른 객체와 나눠야 할 책임을 먼저 식별하고 메시지를 결정한다.
- 메시지는 클라이언트 입장에서 편리하도록 결정되기 때문에 추상적으로 정의될 확률이 높다
- 인터페이스는 클라이언트의 실제 요구사항만을 반영하니 최소한의 크기를 갖게 된다.

코드를 작성할 때 
상향식: `협력 객체의 메서드를 먼저 작성> 클라이언트 코드가 이를 호출`하는 상향식의 작성보다
하향식: `클라이언트의 메서드 호출을 먼저 작성> 빨간 불이 들어온 메서드를 Alt + Enter로 협력 객체의 인터페이스에 추가`

하향식으로 작성하는 것이 인지의 부담도 적고 신속하며 책임 주도 설계와 부합하네요.
IDE의 도움을 받아 많은 분들이 이 방식에 숙달되어 있을 것 같습니다.


### 디미터 법칙
클메시지를 전송할 대상을 잘 골라서 클라이언트가 협력 객체의 구현 변경에 노출되지 않도록 해야 합니다.
```
클라이언트 **C**와 **C**의 메서드 **M**에 대하여, **M**이 메시지를 전송할 대상은 오직 다음과 같다.
- **M**이 인자로 받은 객체
- **M**의 지역 변수
- **C**의 인스턴수 변수 = {this, this의 속성, this의 컬렉션 속성 속 아이템}
```

[관련 격언]
- Don't talk to strangers.
- Only talk to immediate neighbors.
- Use only one dot.

### 묻지 말고 시켜라
- 협력 객체의 상태를 묻기> if문으로 상황에 따른 로직을 실행하기 처럼 코드를 작성하지 말아야 한다.
- 협력 객체는 그 상태에 관해 높은 확률로 정보 전문가이다. 관련 로직은 내가 아닌 정보 전문가가 수행해야 한다.

[관련 격언]
- Tell, don't ask.


### 의도를 드러내는 인터페이스
오퍼레이션명을 어떻게 짜면 좋을지에 대한 가이드입니다. 이 지침도 책임 주도 설계를 따르면 자연스레 따를 수 있습니다.

- "무엇"을 할지를 나타내라
  `isSatisfiedBy`
- "어떻게" 할지를 나타내지 마라
  `isSatisfiedByPeriodCondition`
- 구현에 대한 내용은 캡슐화하고 협력에 관련된 의도만을 표현해야 한다.

### 원칙에 대한 오해
#### 디미터 법칙 / 묻지 말고 시켜라 지침의 맹목적인 준수는 인터페이스의 응집도를 떨어뜨릴 수 있다.

POJO를 오직 데이터를 담기 위한 컨테이너로 인식할 경우, 기차 충돌이 필연적으로 발생하는 것 같습니다.
예를 들어, AWS 람다 서비스는 AWS 이벤트 객체를 람다에게 주입해 주는데, 그 구조는 JSON 따라하기만 한 것입니다.
```
{
  "Records": [
      "s3": {
        "s3SchemaVersion": "1.0",
        "configurationId": "testConfigRule",
        "bucket": {
          "name": "codebucket-paimonganyu-305992497901-ap-northeast-2",
          "ownerIdentity": {
            "principalId": "EXAMPLE"
          },
          "arn": "arn:aws:s3:::example-bucket"
        },
        "object": {
          "key": "GENSHINGIFT.json",
          "size": 1024,
          "eTag": "0123456789abcdef0123456789abcdef",
          "sequencer": "0A1B2C3D4E5F678901"
        }
      }
    }
  ]
}
```
(S3이벤트)

위 이벤트가 표상한 S3 오브젝트를 버킷에서 읽어오려면 객체 내부를 트래버설 해야 합니다.
```
event.getRecords().stream()
                .map(record-> {
                    String bucketName = record.getS3().getBucket().getName();
                    String objectKey = record.getS3().getObject().getKey();
                    // S3Client 호출 ...
                    return json;
                });
```

만약 이 과정을 위임할 수 있는 오퍼레이션이 제공되면 클라이언트는 편할 것입니다.
```
bytes[] object = s3Event.readAllBytes(s3Client);
```

하지만 이벤트 객체가 이벤트의 내용을 표상하는 책임만으로 충분하다면
`readAllBytes`는 이벤트 객체의 응집도를 떨어뜨리는 동떨어진 기능이 됩니다.

**Comment by wooyounggggg** [comment]
https://jojoldu.tistory.com/412

해당 이슈의 마지막에서 논의했던 `객체의 컬렉션을 어떻게 다루어야 하는가?`라는 주제에 관한 해결법 중 하나를 발견하게 되어
글을 공유합니다.
