### ISSUE TITLE
[additional] 참조 투명성 in wikipedia

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#24]
## 연관 챕터
#22 

## 조사 내용
책 p.211의 명령-쿼리 분리 원칙 파트에서, `참조 투명성`이라는 단어를 언급합니다.
이와 관련하여 [위키피디아의 정의](https://ko.wikipedia.org/wiki/%EC%B0%B8%EC%A1%B0_%ED%88%AC%EB%AA%85%EC%84%B1)를 참고하니, 해당 단어가 명령-쿼리 분리 원칙의 핵심 단어로 보이기도 하고, 나아가 함수형 프로그래밍의 기원에 대해서 이해할 수 있는 부분도 있어 해당 내용을 공유합니다.

**Comment by leejaeseung** [comment]
## 함수형 프로그래밍의 역사
함수형 프로그래밍이 왜 대세가 되었고, 이전엔 왜 안 쓰였는지 갑자기 궁금해서 재미삼아 정리해 보았습니다 ㅎㅎ

함수형 프로그래밍은 1980 년대 이전부터 사용되어 왔습니다. 하지만 1970 ~ 1980 년 사이에 소프트웨어를 작성하는 방법이 함수의 합성에서 일련의 명령을 전달하는 방식으로 변하면서 함수형 프로그래밍은 밀려나고 객체 지향이 떠오르게 됐다고 합니다.
(심지어 아래 글에서는 객체 지향에서 사용되는 상속과 is-a 관계를 끔찍하다고까지 표현하네요..ㅋㅋ)
https://tpgns.github.io/2018/03/20/the-rise-and-fall-and-rise-of-functional-programming-composable-software/

- 개인적인 생각으론, 수학에 기초하고 있는 함수형 프로그래밍이 너무 난해해서 보다 쉬운 명령형, 객체 지향형 프로그래밍이 대세가 되었던게 아닐까 합니다.

함수형 프로그래밍이 다시 주목받게된 이유는 AI, 빅데이터, 블록체인 등 많은 데이터를 비동기적이고 안정적으로 처리해야 하는 방법이 필요해졌기 때문이라고 합니다. (함수형 프로그래밍은 부수효과가 없으므로 비동기 처리에 특화)

여기에 더해서 저희 팀 시니어 개발자께서도 의견을 주신게, 함수형 프로그래밍은 매번 새로운(변하지 않는) 객체를 반환하는 특성때문에 객체 지향에 비해서 성능이 떨어질 수 있는데, 최근 기술의 발전으로 함수형 프로그래밍의 성능 이슈가 해결된 것도 있다고 하네요.

**Comment by binchoo** [comment]
Catalog
