### ISSUE TITLE
[question] 객체지향 vs 객체기반

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#27]
## 질문

책에서 객체기반 프로그래밍이라는 단어가 나왔는데, 객체지향과 비교했을 때 장단점이나, 객체기반 프로그래밍의 특징에 대해 더 이야기해 보면 좋을 것 같습니다.

객체지향 대표 언어 : JAVA
객체기반 대표 언어 : JavaScript
위 두 언어의 차이/특징에 대해 생각해보는게 더 쉬울 것 같네요

참고글 : [객체지향 vs 객체기반](https://blog.naver.com/PostView.nhn?blogId=newbongman&logNo=222329975426&parentCategoryNo=&categoryNo=&viewDate=&isShowPopularPosts=false&from=postView)

**책에서의 내용**

객체지향의 경우 **타입 추가**라는 변경의 압력이 강한 경우 -> 다형성을 통해 조건문을 제거할 수 있음.

객체기반의 경우 **오퍼레이션 추가**의 압력이 강한 경우 -> 객체지향이면 상속 계층의 메소드를 모두 수정해야 함.

## 연관 챕터

@caffeine-library/readers-objects

**Comment by JasonYoo1995** [comment]
oh good question

**Comment by leejaeseung** [comment]
## 프로토타입 언어
```
const obj = {
  a: 2,
};

const anotherObj = Object.create(obj);

console.log(anotherObj); // {}
console.log(anotherObj.a); // 2 anotherObj 에는 존재하지 않지만, Prototype Chain 을 타고 올라가 obj 의 a 를 찾음.
```
프로토타입 언어인 자바스크립트에선 모든 객체를 링크로 연결하기 때문에, 하위 객체는 트리를 타고 올라가 상위 객체를 찾을 수 있습니다
(클래스 기반 언어의 상속?) -> 이런 객체간의 링크 관계를 **Prototype Chain** 이라고 합니다.
![image](https://user-images.githubusercontent.com/23518329/167825159-a4cf504c-ce41-404e-a060-fc5468c159ea.png)

프로토타입 언어에선 애초에 모든 객체가 하나의 트리(Object 가 root 인)로 묶여있기 때문에, 객체 조작이 매우 간편합니다.
```
const object = {}  // 코드 단 한줄로 객체가 생성됨.
```
위 코드의 경우에도 클래스 기반 언어였다면 object 를 위한 클래스(틀)를 만들고 생성해야 했겠죠.
모든 걸 객체트리 하나로 표현하기 때문에 **객체기반**이라는 이름이 붙지 않았나 싶네요.

언제 어디서든 객체를 조작할 수 있다는 건 매우 편리하지만, 생각해보면 단점도 존재하겠죠.
모든 객체가 하나의 트리에 묶여 있고, 자식 객체는 root 까지의 모든 부모를 찾을 수 있으며 심지어는 수정까지 가능합니다.
즉, 자식 객체가 상위 객체(prototype) 의 메소드나 변수를 변경할 수 있는 거죠. (이렇게 변경된 메소드는 하위 모든 객체에 영향을 미칩니다.)

프로토타입 기반 언어와 클래스 기반 언어의 차이를 요약하면 아래처럼 되지 않을까 합니다.
상위 객체(클래스)에 구애받지 않는 유연한 프로그래밍 vs 상위 객체(클래스)의 동작을 보장받는 하위 객체

**Comment by wooyounggggg** [comment]
TS 스터디를 하면서 [구조적 타이핑](https://typescript-kr.github.io/pages/type-compatibility.html)을 ts가 지원하는 것을 알게 되었는데, 이 내용과 관련이 있는듯 하여 공유합니다.

**Comment by leejaeseung** [comment]
https://medium.com/@bluesh55/javascript-prototype-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-f8e67c286b67

**Comment by leejaeseung** [comment]
TS 에서 type, interface 의 차이
https://bny9164.tistory.com/48

**Comment by leejaeseung** [comment]
이전에 프로토타입 기반 언어에선 자식이 부모를 조작할 수 있다. 라는 내용에 대해 예시가 부실했던 것 같아 간단하게 테스트해 보았습니다.
![image](https://user-images.githubusercontent.com/23518329/169566220-fb6b719a-319d-434c-a33b-8ed27d5d3b92.png)
위 예시에서 Person 으로부터 생성된 child 는 Person 의 prototype 값인 arg1 을 수정할 수 있습니다.

![image](https://user-images.githubusercontent.com/23518329/169566523-f27dfd9d-6b08-41bf-9198-9ea271cf858b.png)
그리고 모든 객체는 Object 의 자식이기 때문에 빈 객체 object 의 __proto__ 타입에 접근하면, Object 의 toString 메서드를 수정할 수 있었습니다!!
