### ISSUE TITLE
[keyword] 7장 - 객체 분해

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/objects#29]
## 주제

'7장 - 객체 분해'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#28 

@caffeine-library/readers-objects

**Comment by JasonYoo1995** [comment]
# 객체 분해
- 분해 : 큰 문제를 작은 문제로 나누는 것
- 추상화 : 작은 문제들을 큰 문제 하나로 묶는 것

## 1. 프로시저 추상화와 데이터 추상화
- 프로시저 추상화 = 기능 분해 = 알고리즘 분해
- 데이터 추상화 = 타입 추상화(=추상 데이터 타입) or 프로시저 추상화(=객체지향)

## 2. 프로시저 추상화와 기능 분해
- 하향식 접근법
<img src=https://user-images.githubusercontent.com/66045861/166134019-8b4b6017-f7fb-42a0-820e-f593478d575c.png width=700>

- 하향식 기능 분해의 문제점
  - 결합도가 높아, 변경이 어디로 전파되는지 예측하기 어렵다
  - (상호 작용이 아닌) 시간 순서대로 코딩하게 되어, 재사용성이 저하된다
  - 비즈니스 로직과 사용자 인터페이스가 강하게 결합된다 (→ Spring에서 Controller와 Service를 분리)

## 3. 모듈
- 정보 은닉 : 데이터에 직접 접근하지 못하고, 모듈 안에 가둬서 public interface를 통해서만 데이터를 조작할 수 있도록 하는 것
  (→ [Anemic Domain Model보다 Rich Domain Model이 안정적](https://github.com/caffeine-library/objects/issues/18))
- 모듈의 장점
  - 데이터의 변경으로 인한 파급효과가 모듈 밖으로 전파되지 않는다
  - 비즈니스 로직과 사용자 인터페이스라는 두 관심사를 분리해준다
    (이로 인해, 사용자 인터페이스가 변경돼도 비즈니스 로직은 변하지 않는다)
  - 즉, 높은 응집도와 낮은 결합도

## 4. 데이터 추상화와 추상 데이터 타입
- **모듈**은 인스턴스 개념이 없는데, **추상 데이터 타입**은 인스턴스를 구현할 수 있다
<img src=https://user-images.githubusercontent.com/66045861/166134759-46acffdf-d788-468d-a5ea-4d292cf423d6.png width=600>
<img src=https://user-images.githubusercontent.com/66045861/166134820-54258713-9147-4253-851c-db03706dd9a1.png width=300>

- <b>타입 구분 방법</b> : false/true를 입력 받아 **조건문**을 통해 **타입**을 구분

## 5. 클래스
<img src=https://user-images.githubusercontent.com/66045861/166134890-aaf82cef-94aa-42b4-8079-2509e6b533fa.png width=600>

- <b>타입 구분 방법</b> : 직접 타입 이름을 통해 구분

### <b>추상 데이터 타입</b>과 <b>클래스</b>의 차이점
- <b>추상 데이터 타입</b> : 한 오퍼레이션 안에 모든 타입에 대한 로직을 조건문과 함께 구현한다
  → 오퍼레이션 추가가 잦을 때 유리
- <b>클래스</b> : 각 타입이 각자 자신의 로직을 구현한다
  → 타입 추가가 잦을 때 유리
<img src=https://user-images.githubusercontent.com/66045861/166135276-57279b30-824d-4612-a294-9e575aa07ed0.png width=700>

@caffeine-library/readers-objects

**Comment by ngwoon** [comment]
사람은 문제를 해결하기 위해 추상화, 분해 기법을 사용한다. 소프트웨어로 문제를 해결할 때도 이 방법들은 유용하다.

## 프로시져 추상화 & 데이터 추상화

추상화 기법에는 크게 두 가지가 존재한다.

- 프로시져 추상화
    
    소프트웨어가 무엇을 “해야하는지” 추상화한다.
    
- 데이터 추상화
    
    소프트웨어가 무엇을 “알아야 하는지” 추상화한다.
    

추상화 기법을 기반으로 분해 방법을 선택한다.

- 프로시져 추상화를 선택한 경우
    
    기능 분해 방식으로 시스템을 구현한다.
    
- 데이터 추상화를 선택한 경우
    
    데이터 추상화는 두 가지로 구분된다.
    
    - 타입 추상화를 선택한 경우
        
        추상 데이터 타입 분해 방식으로 시스템을 구현한다.
        
    - 절차 추상화를 선택한 경우
        
        객체지향 분해 방식으로 시스템을 구현한다.
        

## 프로시져 추상화 & 기능 분해

기능 분해란 전체 시스템을 커다란 메인 함수로 여기고, 이를 조금 더 구체적인 작은 단위의 프로시져들로 나누는 하향식 분해 방법이다.

### 장점

- 설계 및 구현이 비교적 쉽다.
- 이미 정립된 논리를 설명하는 방법으로 적절하다. (ex 알고리즘)

### 단점

- 현대 시스템은 절대 하나의 메인 함수로 표현될 수 없다.
    
    → 메인 함수의 빈번한 재설계
    
- 비즈니스 로직과 사용자 인터페이스의 결합
- 설계 과정에서 정해져버리는 실행 순서
    - 구현에 집중하는 설계 (설계 본질과 맞지 않게됨)
    - 함수의 재사용성 저하
- 데이터 변경으로 인한 파급효과 예측 x

**기능 분해의 모든 단점은 프로시져 간 결합도가 원인이다.**

## 모듈

[용어 정의 참고](http://www.ktword.co.kr/test/view/view.php?m_temp1=2226)

- 보다 작고 이해할 수 있는 단위로 나뉘어진 것
- 본체에서 분리되어 작은 부분으로 유기적으로 구성되어 있다가, 필요할 때 본체에 합류하여 그 기능을 수행할 수 있는 것
- 통상, 그 자체로 하나의 완전한 기능을 수행할 수 있는 독립된 실체

정보 은닉 개념과 밀접히 연관되어 있다.

정보 은닉의 핵심은, 변경 가능성이 높은 것들을 상대적으로 안정적인 인터페이스 뒤로 숨기는 것이다.

정보 은닉은 숨겨야 할 대상으로 단순 데이터 뿐만 아니라, **변경 가능성**과 **복잡성** 또한 그 기준이 될 수 있다고 소개한다.

모듈의 정보 은닉을 통해 어느 정도 추상화가 가능하지만, 모듈은 태생적으로 “변경” 을 컨트롤하는 구현 기법이므로 추상화 관점에서는 그 한계가 드러난다.

ex) 책 예시의 Employees는 전체 직원에 대한 정보를 은닉하는 모듈. 각각의 직원 정보를 캡슐화하는 인스턴스 개념이 없음

## 데이터 추상화, 추상 데이터 타입, 객체지향

기존 프로시져 추상화에서는 데이터 변경 시 그것의 여파를 측정하기가 어려웠다.

이에 바바라 리스코프에 의해 “데이터 추상화” 라는 개념이 제시되었다.

데이터 추상화는 타입 추상화와 절차 추상화로 나뉜다.

타입 추상화 → 추상 데이터 타입 분해

절차 추상화 → 객체지향 분해

### 추상 데이터 타입, 객체지향

추상 데이터 타입은 오퍼레이션을 기반으로, 타입을 추상화하는 분해 기법이다.

직원이라는 타입은 모두 급여 계산이라는 동작을 행할 수 있어야 한다. 급여 계산 동작을 기반으로 정규 직원과 아르바이트 직원을 “직원” 이라는 추상화된 타입으로 묶는 분해 방식은 추상 데이터 타입 정의에 해당한다.

객체지향은 타입을 기반으로, 오퍼레이션을 추상화하는 분해 기법이다.

정규 직원, 아르바이트 직원 타입을 명확히 분리하고, 이들이 공통적으로 행할 수 있는 급여 계산 오퍼레이션을 추상화해두고 각 타입에 맞게 따로 구현하는 분해 방식은 객체지향 분해 방식에 해당한다.

### 추상 데이터 타입 vs 클래스

추상 데이터 타입과 클래스의 가장 큰 차이점은 “데이터와 기능의 분리” 이다.

추상 데이터 타입은 보통 “타입 변수” 를 통해 추상화된 타입을 세부적으로 지정한다. 따라서 추상 데이터 타입의 인터페이스 오퍼레이션에는 분기 처리가 들어가는 경우가 많다.

객체지향은 “상속”과 “다형성”을 통해 추상화된 오퍼레이션 중 실제 메세지를 처리할 오퍼레이션을 선택한다.

> 그렇다면 항상 객체지향이 옳고 추상 데이터 타입이 그를까?
정답은 아니다. 애플리케이션의 성질에 따라 다르다.

객체지향은 타입 추가에는 유연하지만 오퍼레이션 추가에는 좋지 않다. 부모 클래스에 하나의 
오퍼레이션을 추가하면, 이를 상속하는 모든 자식 클래스에 이를 구현해주어야 한다.

추상 데이터 타입은 오퍼레이션 추가에는 유연하지만, 타입 추가에 좋지 않다. 하나의 타입이 추가된다면, 타입 변수의 가짓수가 늘어나고 이 타입 변수를 활용하는 외부의 모든 곳에 변경의 영향이 미친다.

따라서 내가 설계하고자 하는 애플리케이션의 변경 압력이 “타입 추가”에 관한 것인지, “오퍼레이션 추가”에 관한 것인지를 고민하고, 객체지향 혹은 추상 데이터 타입 분해를 결정하자.
>

**Comment by wooyounggggg** [comment]
#5 의 내용과 연관이 있어 코멘트 남깁니다.
