### ISSUE TITLE
[question] 추상 데이터 타입(Abstract Data Type)?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#30]
## 질문
책 p.218에서 시스템을 분해하는 방법의 하나로 데이터 추상화를 중심으로 하는 시스템 분해를 언급하고,
그에는 추상 데이터 타입(Abstract Data Type)이라고 부르는 타입 추상화와, 객체 지향이라고 부르는 프로시저 추상화를 언급합니다.

이중, 추상 데이터 타입은 무엇인가 궁금함이 생겨 질문 남깁니다.

## 연관 챕터
#28

**Comment by JasonYoo1995** [comment]
#29 참고
