### ISSUE TITLE
[additional] YAGNI - You Aren't Gonna Need It

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#33]
## 연관 챕터
#31

## 조사 내용
책에서 중복 할인 기능을 추가 적용하는 `OverlappedDiscountPolicy` 예제가 있었습니다.
이 책을 읽으면서 예전부터 든 생각이, '할인 정책을 여러 개 적용할 수 있는 경우엔 어떡하지?', '미리 List 로 받을 수 있게 해놓는게 유연하지 않을까?' 라는 생각이 들었었습니다.
`OverlappedDiscountPolicy` 예제를 보고 나니 이전에 했던 생각이 오버 프로그래밍이었다는 생각이 들더라구요. 이와 관련해 사내 스터디에서 YAGNI 원칙에 대해 했던 얘기가 떠올라 공유해 봅니다.

YAGNI 원칙을 풀어 쓰면 "**그것은 필요없을 것이다**" 인데, 이는 미래에 쓰일지 안쓰일지 모르는 것에 대해 굳이 만들어두지 말라는 원칙입니다. 개발을 하다보면 이것저것 너무 많은 걸 생각하고 대비하다 보니 코드가 장황해지는 경우가 많은데 그럴 때마다 이 원칙을 생각해보면 좋을 듯 합니다. 
(최악의 경우, 미래에 쓰일 거라고 생각했던 코드가 오히려 버그를 일으키는 경우도 있다고 하네요..)

중복 할인 기능의 경우에도 처음부터 할인 정책을 List 로 해뒀다면 중복 할인 기능이 추가되기 전까지 모든 로직을 List 로 처리해야 하는 불편한 상황이 생길 수도 있었을 듯 하네요. 

YAGNI 에서 피하라고 하는 코드의 유연성을 **유연성 매커니즘**이라고 표현하는데, 이 유연성 매커니즘의 범위에 대해서도 생각해보면 좋을 듯 합니다.
- **코드의 공통화, 공통 모듈로 코드 합치기**
- **코드의 추상화**

처음엔 이 정도까지만 유연성 매커니즘을 고려하면 되지 않을까 했는데, 시니어분들은 더 넓은 범위에서의 유연성 매커니즘을 말씀하시더군요.
- **파라미터 추가**
- **타입의 제한(bound) 등**

내용과 관련해서, 코드를 너무 유연하게 설계해서 오히려 독이 되었던? 경험이 있으신지 궁금합니다

**Comment by JasonYoo1995** [comment]
저는 회사에서 Node.js 프로젝트를 진행하면서
무려 40줄이나 되는 코드가 3번 중복 되는 경우가 있었고
인텔리제이가 알아서 중복 코드를 감지해서 경고를 해주기도 했습니다.
그래서 제가 이 코드를 하나의 코드로 따로 빼고
기존의 3군데에서 import하여 사용하도록 코드를 수정한 뒤 코드 리뷰를 받았는데
해당 코드는 실제 핵심 로직에 관여하는 코드라기보다는
Dummy 샘플 서버에서만 사용하는 코드로서 
**재사용하기 위한 공식 코드가 아니므로**
중복된 상태 그대로 두고 lib 패키지에 옮기지 말라고 하셔서 원상 복귀 했던 기억이 있습니다.

(**재사용하기 위한 공식 코드**들은 lib 패키지에 따로 관리됐는데
비즈니스 로직이 의존하는 low level의 로직들이 포함된 패키지였습니다.)

이와 같이 '중복 코드를 최소화한다'와 같은 유연한 설계 법칙을 기계적으로 따르는 것이 아니라
코드의 목적/용도/역할에 따라 거시적인 관점에서 정답이 얼마든지 달라질 수 있다는 걸 볼 수 있었습니다.
 
그 외에도, 너무 타이트하고 어려운 수준의 설계 원칙을 프로젝트 전체에 걸쳐서 적용하다 보면
팀원들이 못 따라올 수도 있으므로
팀의 수준에 따라 그 기준이 달라질 수도 있을 것 같습니다.

---

이외에 '이상'과 '현실' 간의 타협 혹은 '완성도'와 '데드라인' 간의 타협의 사례가 있었는데
여러 서버가 통신하는 마이크로서비스 구조에서 **성능 테스트**를 수행할 때 
단위 테스트까지만 수행하고 통합 테스트는 수행하지 않는다는 팀 내 규칙이 있었습니다.
여기서 단위 테스트는 서버 1대에 대한 성능 테스트를 의미하고
통합 테스트는 여러 서버를 거쳐서 들어갔다 나올 때까지 걸리는 시간에 대한 테스트를 의미합니다.
통합 테스트를 하지 않는 이유는
다른 팀의 서버를 함부로 쓰기 어려운 상황도 있고
성능 테스트에서 발생시키는 트래픽의 특성과
실제 라이브에서 발생하는 트래픽 간의 특성이 다르기 때문에
통합 테스트를 수행하는 것이 큰 의미가 없기 때문입니다.

단위 테스트의 결과만을 보고, 통합 테스트의 결과를 예상하는 정도까지만 생각하고
예상되는 서버의 대수 만큼 클라우드 지원팀에게 서버를 요청하여 라이브 배포를 합니다.
그럼 실제 라이브 배포에서 진짜 정확한 성능 결과를 알 수 있게 됩니다.

---

(작성 중)
