### ISSUE TITLE
[keyword] 9장. 유연한 설계

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#35]
## 주제

`9장 - 유연한 설계`를 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터
#34

**Comment by binchoo** [comment]
## 서비스 로케이터 구현 방안

서비스 로케이터에는 응용이 필요로 하는 의존성을 모아둡니다. 
이 의존성들은 요구사항에 따라 수시로 변경될 수 있으므로 서비스 로케이터는 **커스터마이징이 가능**해야합니다. 

대표적으로 2가지 방안을 떠올릴 수 있습니다.
- 서비스 로케이터에 DI를 위한 인터페이스를 마련: 생성자 주입, 수정자 주입.
  **ServiceLocator.java**
  ```java
  public class ServiceLocator {
    public ServiceLocator(DrivingPort service, DrivenPort infra) { ...} 
    public getServicePort() { ...}
    public getInfraPort() { ...}
  }
  ```

  **Main.java**
  ```java
  public static void main(String... args) {
    // 생성자 주입으로 의존성 커스터마이징
    ServiceLocator serviceLocator = new ServiceLocator(new ServiceA(), new InfraA());
    UI ui = new UI(serviceLocator);
    ...
  }
  ```
- 추상 서비스 로케이터: 추상 서비스 로케이터를 상속하는 클래스에서 의존성 커스터마이징.
  **ServiceLocator.java**
  ```java
  public abstract class ServiceLocator {
    public abstract DrivingPort getServicePort();
    public abstract DrivenPort getInfraPort();
  }
  ```

  **ServiceLocatorA.java**
  ```java
  public ServiceLocatorA implements ServiceLocator {
    public DrivingPort getServicePort() {
      return new ServiceA(getInfraPort());
    }
    public DrivenPort getInfraPort() {
      return new InfraA();
    }
  }
  ```

  **Main.java**
  ```java
  public static void main(String... args) {
    // 생성자 주입으로 의존성 커스터마이징
    ServiceLocator serviceLocator = new ServiceLocatorA();
    UI ui = new UI(serviceLocator);
    ...
  }
  ```

## 서비스 로케이터 배치 방식
서비스 로케이터에 담아 둘 의존성들은 요구사항에 따라 수시로 변경됩니다.
이러한 변경 발생 시, 변경의 전파를 효과적으로 차단하면 수정해야 할 패키지(모듈)이 줄어듭니다.

앞에서 2가지 구현 방식을 소개했는데요, 각자 서비스 로케이터 관련 클래스들을 배치하는 방식이 다릅니다.


### 의존성 주입을 통해 커스터마이징


### 상속을 통해 커스터마이징
