### ISSUE TITLE
[additional] 중개자 패턴

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#36]
## 연관 챕터
#34

## 조사 내용
책에서 중개자 패턴에 대해 잠시 나왔는데, 중개자 패턴의 전체적인 개념을 추가적으로 정리해 봅니다.

## 중개자 패턴이란?
- 여러 클래스들의 복잡한 연관 관계를 하나의 **중개자(Mediator)**에서 관리하는 패턴
- 클래스들의 관계가 M:N -> M:1 이 된다.

![image](https://user-images.githubusercontent.com/23518329/168253329-013d81cd-164a-4bf6-9c72-37edb3a93b1f.png)
위처럼, A, B, C, D, E 간에 복잡한 관계를 Mediator 에서 메소드를 새로 관리하면서 간단하게 변환합니다.
따라서 각 클래스에선 Mediator 클래스만 주입받으면 싱글톤 객체를 사용하는 것처럼 메소드를 사용할 수 있습니다.

**장점**
- 각 클래스의 외부 의존성이 하나로 뭉쳐진다. (의존성 주입을 5개 받던 걸 1개로 수정 가능!)
- 어떤 클래스의 메소드를 쓰는지 몰라도 된다. 단지 Mediator 에서 제공하는 기능을 사용할 뿐이다. (마치 util 클래스를 쓰는 것처럼)

**단점**
- Mediator 에 모든 의존성이 모이고, 프로젝트가 거대해 진다면..? 오히려 복잡도가 올라가지 않을까?
- 의존성 서킷의 위험성 : 각 클래스는 다른 클래스를 모르므로 의존성이 돌고 돌 수 있다고 한다. (Meditor 는 의존성 서킷을 체크할 방법이 없음)
- 추가로, 의존성의 순서를 알 수 없기 때문에 Mediator 에서 주입되는 클래스들은 Lazy 로 선언한다고 하네요. (사내 코드 기준)

**Comment by binchoo** [comment]
https://github.com/spring-projects/spring-framework/blob/4750a9430cdae9156d1e7fc32cec2c11ba2b8514/spring-test/src/main/java/org/springframework/test/web/servlet/request/MockMvcRequestBuilders.java

**Comment by leejaeseung** [comment]
/**
 * 중재자 클래스.
 * 다른 클래스와 상호 참조하는 구조이기 때문에 인스턴스를 생성하는데 문제가 생기기 쉽다.
 * 이 클래스의 인스턴스가 다양한 곳에 주입돼어 역할을 할 수 있기 때문에 다른 인스턴스 보다 먼저 생성이 되는 편이 낫다.
 * 따라서 주입 받는 모든 객체는 @Lazy 속성으로 선언돼야 한다.
 */
