### ISSUE TITLE
[question] 개발 루틴은 어떻게 하고 계시나요?

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#39]
## 질문

최근들어 개발을 할 때면 너무 막무가내로 코드를 짜는 듯한 느낌을 많이 받고 있습니다..
제가 생각하는 가장 이상적인 개발 루틴은 **설계 -> 테스트 케이스 구상(TDD) -> 기능 개발 -> 테스트코드 작성 -> 리팩토링** 의 순서인데, 사실상 중간을 건너뛰고 진행하는 경우가 대부분이었던 것 같습니다. (시간 상 혹은 너무 간단한 기능이라? 등등의 이유로)
그래서 뭔가 저만의 개발 루틴을 정립해볼까 하고 있습니다. **기능 개발 -> 테스트코드 작성 -> 리팩토링** 의 순서는 지키자! 정도?

확실한 자기만의 개발 루틴이 만들어지면 더 생산적으로 개발할 수 있을 것 같아 서로의 개발 루틴을 서로 공유해보면 어떨까 합니다!
ex) 제 팀원분은 기능 개발 전에 기능을 추가할 구간에 TODO 를 끼워넣는 작업을 하시더라구요. 되게 신기했습니다.

## 연관 챕터

x

@caffeine-library/readers-objects

**Comment by JasonYoo1995** [comment]
해당 issue는 랜덤 Repository에 적어주셔도 좋습니다
랜덤 Repository 주소 : https://github.com/caffeine-library/random/issues

**Comment by leejaeseung** [comment]
문서 작성할 때 TODO? 하나의 기능에 하나의 문서
테스트를 해야한다! 를 TODO 로

스펙 리뷰 문화 : 이슈를 받으면 그 이슈에 대해 스펙 리뷰를 해야함 -> 픽스가 되면 개발 진행
개발 검토 문서화 -> 기획 분들이랑 이러이러케 개발하겠다. -> 검토 최종, 검토 최최종. 개발하면서 계속 피드백

DM 으로 스펙에 대해 주고받고, 확정이 되면 공식 문서화
이슈 레포를 파서, 기획자 분들이 이슈 레포로 이슈를 남김
