### ISSUE TITLE
[keyword] 2장 - 객체지향 프로그래밍

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#4]
## 주제
`2장 - 객체지향 프로그래밍`을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#3

**Comment by binchoo** [comment]
2장에서 언급된 전략들이 갖는 트레이드 오프를 정리합니다. 

## Trade-offs

###  추상화를 통한 다형성 지원
- 단점
  - 소스코드 의존성과 제어의 흐름이 같지 않아서 가독성의 저하. 
  - 객체 간 연결해주는 코드(main 함수, DI/DL 프레임워크)를 확인해야 프로그램을 이해할 수 있다. 
- 장점
  - 세부 내용을 무시한 채 고수준에서 정책을 묘사하고 이것을 소스 코드 그대로 구현한다.
  - 하위 구현은 상위 정책의 틀에 맞추어진다. 따라서 기본 구조의 수정 없이 새로운 기능을 쉽게 추가한다.
 
관련 개념: 상속, 인터페이스, 다형성, 템플릿 메서드 패턴, lazy binding

### 예외 정책 구현시 템플릿 메서드 패턴의 트레이드 오프
예외 정책을 구현할 때 무심코 추상 클래스를 상속해 템플릿 메서드 패턴을 적용했더니 어떤 문제점이 나타났습니다.

- `NoneDiscountPolicy`는 할인 정책이 없는 예외 상황을 묘사하기 위해 고안됨.
- 부모 추상 클래스 `DiscountPolicy`를 상속하여 `getDiscountAmount()`를 구현하였더니 메서드 `calculateDiscountAmount()`의 제어를 받게 되었고, 결과적으로 `getDiscountAmount()`는 **불용코드**가 되었음.

  ```java
  public class NoneDiscountPolicy extends DiscountPolicy {
    @Override
    public Money getDiscountAmount(Screening screening) {
      return Money.ZERO;
    }
  }
  ```

  ```java
  public abstract class DiscountPolicy {
    public Money calculateDiscountAmount(Screening screening) {
      for (DiscountCondition each : conditions) {
        if (each.isSatisfiedBy(screening)) {
          return getDiscountAmount(screening); // NoneDiscountPolicy::getDiscountAmount()는 호출될 수 없다.
        }
      }
        return Money.ZERO;
    }

    abstract protected Money getDiscountAmount(Screening screening);
  }
  ```
- `NoneDiscountPolicy`는 `DiscountPolicy`가 제공하는 **틀**에 개념적으로 호환되지 않음에도, 개발자가 이를 판단하지 못 했기 때문임.

- 책이 제시한 리팩토링 방법은 `DiscountPolicy`를 인터페이스로 빼고, 이 인터페이스에 대한 `NoneDiscountPolicy` 구현체와 `DefaultDiscountPolicy` 추상 자손 클래스로 분화시켰음.
