### ISSUE TITLE
[keyword] 11장. 합성과 유연한 설계

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#45]
## 주제

`11장. 합성과 유연한 설계`을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터
#43 

@caffeine-library/readers-objects

**Comment by JasonYoo1995** [comment]
- 지난 시간에 나눈 내용 중 '전략 패턴'의 장점이 "기존 코드의 변경 없이 타입만 추가할 수 있다"는 것이라고 했는데
  그것 외에도 "의존성이 컴파일 타임이 아닌 런타임에 결정돼 더 유연한 설계가 가능하다"는 것도 있는 것 같습니다.
- 이 책에서 인터페이스는 2가지 의미로 쓰이는 것 같습니다.
  1. class와 대비되는 단어로서의 interface
     <img src=https://user-images.githubusercontent.com/66045861/170844746-a8a32ab8-1d72-4835-8baa-668fb9e0308f.png>

  2. 특정 class의 public method들의 묶음
     <img src=https://user-images.githubusercontent.com/66045861/170844765-66f1f5f8-0368-4265-9e20-5ff605492846.png>
