### ISSUE TITLE
[keyword] 12장 - 다형성

### ISSUE THREAD

**Issue by emiling** [caffeine-library/objects#48]
## 주제

`12장 다형성`을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#47 

@caffeine-library/readers-objects

**Comment by leejaeseung** [comment]
##C++ 에서 이름 숨기기(name hiding) 으로 얻는 이점이 뭘까?

관련 링크 : https://stackoverflow.com/questions/28586123/name-hiding-in-c-vs-java

이름 숨기기가 없는 경우
```
struct Base {};
struct Derived : Base {void f(int);}
```
Derived 를 구현한 개발자는 f() 가 int 에 대해서만 동작하길 기대했을 것입니다.
하지만 어느 순간 Double 에 대해서도 성공한다면
```
Derived d;
d.f(42.0);  // OK: double converts to int
```
f() 메소드를 사용한 사람은 혼란이 오게 되고, 나중에 Base 에 f() 메소드가 새로 추가된 걸 알게 될 겁니다.
```
struct Base {
    void f(double);  // Completely unrelated to D::f
};
```
이는 Derived 클래스를 만든 개발자의 의도와는 다를 수 있기 때문에, 이름 숨기기로 제한할 수 있습니다.

위 예시를 보니 이름 숨기기를 제공하는 이유가 납득되긴 하더군요.
이름 숨기기의 유/무는 모두 장단점이 있는 것 같아 언어의 철학 차이가 아닐까 싶습니다.

**Comment by leejaeseung** [comment]
## 리팩토링을 하다보면 클래스 내부에 private 메소드를 많이 넣게 되는데, 이 또한 self send 처럼 동작하지 않을까? 그렇다면 매번 private 메서드가 호출될 때마다 self 부터 찾아올라가지 않을까?

책을 읽다가 동적 메서드 탐색 부분을 읽고 문득 위 의문이 떠올랐습니다.
결론은 **아니다** 입니다.

private 메서드는 컴파일 타임에 해당 **클래스 내부에 있다는게 확실히 정해지기 때문에** 동적 메소드 탐색 시에 해당 클래스 내에서 메서드를 찾게 됩니다.
관련 링크 : https://coderanch.com/t/219390/certification/Dynamic-Method-lookup-private-methods
> For private and static members, the compiler will start with the declared type not the run type. In the above case, the declared type was of Class B. Hence, we execute the f() method found in Class B.

**Comment by wooyounggggg** [comment]
### P.389 
상속은 재사용을 위해 사용하는 것이 아니라, 클라이언트 관점에서 인스턴스들을 `동일하게 행동하는 그룹으로 묶기 위해` 사용한다
