### ISSUE TITLE
[additional] 객체 지향은 항상 변경에 용이한가?

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#5]
## 연관 챕터
#1

## 조사 내용
책 p.26에서 절차 지향과 객체 지향을 비교하며, 절차 지향이 객체 지향에 비해 늘 변경과 확장에 불리하다는 뉘앙스를 띄고 있습니다.

하지만 이전에 책 `클린 코드`를 공부하면서, [객체와 자료구조의 차이](https://github.com/wooyounggggg/clean-code/issues/18#issuecomment-1065195139)에 관한 내용을 읽으며 객체 지향적이라고 해서 항상 절차 지향 프로그래밍보다 
변경이나 확장 측면에서 유리한 것만은 아니라는 점을 이해하고 관점을 넓힐 수 있게 되어, 내용을 공유합니다.

**Comment by leejaeseung** [comment]
공유해주신 글 잘 읽어 보았습니다!
내용을 정리해보면 절차지향, 객체지향의 단점은 아래와 같겠네요.

절차 지향 : 새로운 클래스가 추가되면 Geometry 의 내부 구현을 바꿔야 한다. - 클래스의 변화에 취약함
객체 지향 : 새로운 메서드가 추가되면 모든 자식 객체들에 적용해야 한다. - 상속의 강제성?
-> Shape 에는 넓이를 구하지 못하는 경우도 존재할 수 있는데, 그런 Shape 클래스가 추가될 경우 area 메소드를 구현하기 매우 애매해지지 않을까 싶습니다.

코드를 보면서, 두 문제점을 모두 해소하려면 어떻게 할 지 생각해 보았는데요.
```
public class Square {
    public Point topLeft;
    public double side;
}

public class Rectangle {
    public Point topLeft;
    public double height;
    public double width;
}

public class Circle {
    public Point center;
    public double radius;
}

public class Geometry {
    public final double PI = 3.141592653589;
    
    public double area(Square shape) {
        return shape.side * shape.side;
    }

    public double area(Rectangle shape) {
        return shape.height * shape.width;
    }

    public double area(Circle shape) {
        return PI * shape.radius * shape.radius;
    }
}
```
이렇게 각 클래스들의 기능(area 구하는 등)에만 집중해 기능 별로 메소드를 나누면 클래스가 변경되어도 변경된 메소드만 수정하면 되고, 새로운 기능(메소드)이 추가되더라도 Geometry 클래스에 메소드를 추가하면 되어서 해당 기능이 필요한 클래스만 유연하게 적용할 수 있겠네요. (+ 절차지향에서의 Exception 을 처리할 필요도 없어졌습니다)

최근 유행하는 함수형 프로그래밍의 모습이지 않나 해서 공유드려봅니다.

**Comment by wooyounggggg** [comment]
@leejaeseung
질문 - 작성해주신 예제에서 어떤 부분이 함수형 프로그래밍의 모습을 띄게 되는건가요?

**Comment by leejaeseung** [comment]
저도 함수형 프로그래밍을 많이 알진 못하지만, 제가 이해한 함수형 프로그래밍은 순수 함수만을 사용해 메소드를 읽는 것 만으로도 그 코드의 동작을 직관적으로 알 수 있게 프로그래밍하는 것입니다.

함수형 프로그래밍에선 함수 내부에서 어떤 사이드 이펙트도 없기 때문에 항상 함수가 수행하는 값만을 얻을 수 있죠. (해당 함수에서 다른 예외를 생각하지 않아도 됩니다)
그런 관점에서 위 코드는 area 메소드가 단지 파라미터로 받은 Shape 의 넓이값만을 반환하기 때문에 함수형 프로그래밍이라고 생각하였습니다.
