### ISSUE TITLE
[additional] assertion 에 관하여

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#51]
## 연관 챕터
#49 

## 조사 내용
책에선 사전 조건, 사후 조건을 검증하기 위해 assert 를 사용하고 있습니다.
리팩토링 책에서도 리팩토링 전/후가 동일함을 검증할 때 assert 를 사용하라고 하는데, 이 때 assert 에 들었던 의문을 공유합니다.

#### 의문 : assert 를 어떨 때 사용하면 좋을까?
- 당연히 참인 경우만 assertion 을 사용한다
  1. 주석이나 테스트 코드를 작성하는게 낫지 않을까? 굳이..
- 오류가 날 지 모르는 곳에 assertion 을 사용한다
  1. 비정상 동작을 수행하지 않으므로 참사를 막을 수 있을 듯..?
  2. 너무 남발하면 자잘한 부분에서 assertion 이 걸려 실제 동작에 지장이 있을 수도?

위 의문은 assert 코드를 함부로 넣었다가 실제 프로덕션 환경에서 assert 때문에 크리티컬한 오류가 발생할지도 모른다는 생각때문이었습니다.
하지만 자바의 경우 실행 시에 `-ea` 옵션을 주어 assert 를 키고 끌 수 있어 개발/베타 환경에서 assert 문을 모두 검증하고, 프로덕션 환경에선 assert 문을 무시하게 한다고 하네요. 실제로 많이 사용되고 있다고 합니다.

자바스크립트에도 assert 를 쉽게 끄고 킬 수 있는 라이브러리가 있네요.
https://github.com/TritonDataCenter/node-assert-plus

추가로, if 문과 assert 의 차이에 대해 의문이 드네요.
if 문으로도 특정 조건에 대해 예외를 던질 수 있지만 assert 는 절대 해당 조건으로 동작하지 않게 함으로써 프로덕션 환경 이전에 맞지 않는 조건을 걸러내겠다는 차이가 있는 것 같습니다.

**Comment by JasonYoo1995** [comment]
비즈니스로직 검증 코드 vs 유효성 검증 코드 -> 분리
에러 던지기 vs 안 던지기 vs 로그 남기기 -> ON/OFF
