### ISSUE TITLE
[additional] atomic 하지 않은 ts의 primitive type

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#53]
## 연관 챕터
#49 

## 개요
p.436에서 `타입`에 대하여 다룹니다.
이와 관련하여, ts에서 타입을 정의하는 관점이 새롭게 느껴진 부분이 있어 간략하게 공유합니다.

### custom literal type
ts에서는 아래와 같은 custom literal type을 정의하고 사용할 수 있습니다.
```typescript
type One = 1;
type A = 'A';

const funcWithOne = (one: One) => {
    console.log(one);
}

const funcWithA = (a: A) => {
    console.log(a);
}
```

One type의 파라미터를 전달받는 funcWithOne 함수는, 1이라는 값이 할당된 One 타입의 변수만 넘겨받는 것이 가능하며
A type의 파라미터를 전달받는 funcWithA 함수는 'A'라는 값이 할당된 A 타입의 변수만 넘겨받을 수 있습니다.

아래의 예시를 보시면, 개략적으로 literal type이 어떻게 사용되는지 이해하실 수 있을 것 같습니다.

![image](https://user-images.githubusercontent.com/19742896/173173747-40564028-3ef1-41cc-a4d4-74dc8855cea9.png)

### ???
저는 이러한 예시를 보고 조금 황당했던 기억이 나네요.
값 하나 또는 몇 개만 받을 수 있는 타입이 일반적인 literal 상수나 배열과 다른게 뭐야? 라는 의문이 생길 수 밖에 없었고, 처음봤을 당시에 '이런게 있구나' 정도로 넘겼던 것 같습니다.

최근에 effective typescript 책을 보면서, 왜 타입스크립트가 이러한 방식으로 커스텀 타입을 정의하는지 이해하게 되었습니다.

### 타입은 값들의 집합이다
이펙티브 타입스크립트에서는, `타입은 값들의 집합이다`라고 이야기합니다. 사실 이는 기존에 이미 존재하는 개념이지, 새롭게 발견된 개념은 아닙니다.(책 p.437의 외연에서도 비슷한 개념을 언급하고 있습니다.)

하지만 자바에서는 이러한 개념을 클래스에 대해서만 구현할 수 있습니다.
보통 상속을 통해 집합 관계를 구성할 수 있죠. 그러나 primitive type에 대해서는 개발자가 임의의 집합 관계를 정의하는 것이 불가능합니다.

반면 타입스크립트는 이러한 집합 관계를 객체 뿐 아니라 primitive type까지 포함하여 모든 값에 대해 적용할 수 있도록 커스텀 타입을 지원하고 있습니다. 이를테면, js에 Int라는 개념이 존재하지 않지만 이를 아래와 같이 새롭게 정의할 수 있습니다.

```typescript
type Int = 0 | -1 | -2 | -3 | ... | 1 | 2 | 3 | ...
```

즉, 흔히 우리가 primitive type으로 사용해오던 int나 string 등의 타입을 atomic하게 바라보는 것이 아니라 더 작은 개별 단위의 값들의 모음이라고 이야기하고 있습니다.

그렇기 때문에 다음의 One 타입은
```typescript
type One = 1;
``` 
아래와 같이 이야기 할 수 있습니다.

1. 숫자 1이라는 값의 집합
2. type One ⊂ type Number

AB 타입은
```typescript
type AB = 'A' | 'B';
``` 
아래와 같이 이야기 할 수 있습니다.

1. 문자열 'A'와 문자열 'B'라는 값들의 집합
2. type AB ⊂ type string

또한 string 타입은 아래와 같이 이야기 할 수 있습니다.
1. 모든 문자열들의 집합

**Comment by JasonYoo1995** [comment]
TS에서 String Type의 Union -> 자바에서 Enum와 비슷?

**Comment by emiling** [comment]
<img width="808" alt="스크린샷 2022-06-12 오후 1 50 54" src="https://user-images.githubusercontent.com/30731518/173215021-7ddf345f-29d2-4c87-9a10-b584110e022e.png">

https://yceffort.kr/2020/09/typescript-enum-not-treeshaked
