### ISSUE TITLE
교재 선정 & 스터디 방식 & 스터디 요일 및 시간 결정

### ISSUE THREAD

**Issue by JasonYoo1995** [caffeine-library/objects#55]
교재 선정 & 스터디 방식 & 스터디 요일 및 시간 결정

**Comment by JasonYoo1995** [comment]
## 스터디 방식
1. 책 하나를 정해서 같은 범위 만큼 읽어와서 아무나 이야기 하기
2. 책 하나를 정해서 같은 범위 만큼 읽어와서 한 사람만 이야기 하기
3. 책 없이, 각자 일주일 동안 공부한 내용 혹은 업무에서 활용한 내용 공유하기
4. 1~3번의 하이브리드 방식

**Comment by JasonYoo1995** [comment]
## 교재 선정
- 경원
  - 토비 스프링
  - DDD 관련 서적
- 재빈
- 우영
- 재승
- 관우
- 유진

**Comment by JasonYoo1995** [comment]
## 스터디 요일 및 시간
- 토
  - ?
- 일
  - 오후 4~6시

**Comment by leejaeseung** [comment]
팀원들이 공유해 준 신입 개발자가 읽으면 좋은 책들 공유합니다~!
![image](https://user-images.githubusercontent.com/23518329/174303867-4b222b95-1641-480d-a89d-ff85af72bdde.png)
![image](https://user-images.githubusercontent.com/23518329/174303919-801b6081-bb85-4f54-8514-de20b23ae21f.png)
