### ISSUE TITLE
[question] 기존 레거시 코드를 어떻게 이해하시나요?

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#59]
## 질문
현업에선 유지보수를 위해 다양한 패턴이 적용되어 코드가 상당히 복잡한 구조를 갖게 되는데, 복잡하고 방대한 코드를 이해하는게 쉬운 일이 아니라는걸 뼈저리게 느끼고 있습니다.
기존 프로젝트에 랜딩할 때 어떤 방식으로 하셨는지 궁금합니다.
(코드의 구조에 대한 설명을 문서화하면 이해를 도울 수 있지 않을까 싶기도 하네요.)

## 연관 챕터

#57

@caffeine-library/readers-objects

**Comment by JasonYoo1995** [comment]
(본 글은 별도의 발표를 하지 않을 예정이니, 6월 19일 모임 때 그냥 다같이 간단히 읽고 넘어가주세요 🧑)

저는 처음에는 모든 코드를 이해하려고 하였는데
그건 현실적으로 불가능하고
해당 프로젝트가 최초로 생성되었을 때 만들어진 **최초 코드**들이 있을 것이고
점점 요구사항이 추가되면서 **덧붙여진 코드**들이 있을 겁니다.
**덧붙여진 코드**들은 무시하고 **최초 코드**만 이해해도 된다고 봅니다.
그러고 나서 **덧붙여진 코드**를 이해하는 것은
본인이 맡은 일감과 연관된 코드들만 추가적으로 이해하면 되는 것 같습니다.
그게 반복되다 보면, 점진적으로 도메인 지식과 코드를 자연스럽게 이해하게 되는 것 같습니다.
또한 저수준의 코드보다는 고수준의 코드를 먼저 이해하는 것도 하나의 방법인 것 같습니다.

**Comment by ngwoon** [comment]
입사하고 지금까지 계속 프로젝트 하나를 인수인계받고 있습니다. 그 과정에서 느낀 점들을 말씀드려보고 싶네요.
* (핵심을 잘 요약한) 문서화는 매우 중요하다.
 * 프로젝트를 인수인계 받는다는 건 CI/CD, 로그 및 성능 모니터링, 운영 중 타 부서 문의 처리, 코드 분석 등 많은 것들을 파악해야 하는 업무임을 깨달았습니다. 이 중 저도 코드 디테일을 파악하는데 시간이 많이 들고 있습니다 ㅠㅠ
 * 이러한 것들이 정갈하게 문서화 되어 있다면 해당 문서를 통해 개요를 파악하고, 디테일한 내용을 살펴보면서 모르는 것들을 질문하는 인수인계가 가능해집니다. 인수인계를 해주는 사람과 받는 사람의 시간을 동시에 절약할 수 있는 방법인 것 같습니다.
*  코드를 파악할 때, 사용되는 용어의 의미 & 시퀀스 다이어그램과 함께 코드를 본다.
 * 이번 주 동안 코드 이해를 목표로 삼았었는데, 도메인 지식도 많이 부족하고 누군가의 코드를 보고 이해하는 것도 익숙치 않다 보니 속도가 정말 느렸습니다.
 * 시행착오를 겪으면서 느낀 점은, 파악하고자 하는 코드의 도메인 지식과 관련된 용어 정리 문서와 시퀀스 다이어그램이 있으면 많이 도움이 된다는 것입니다.
 * 시퀀스 다이어그램(하나의 요청-응답의 flow를 표현)을 보면서 코드의 전체적인 흐름을 대략적으로 파악하고, 여기서 이해가 안되는 파라미터 등이 있다면 용어 사전을 통해 알아냅니다. 전체적 흐름을 살펴본 뒤에는 실제 코드와 시퀀스 다이어그램을 대조하면서 각 코드가 시퀀스의 어느 부분에 해당하는지를 눈으로 확인합니다. 
 * 물론 코드의 세세한 내용을 전부 파악하기 위해서는 유지보수 중간중간 코드를 계속 해석하고 살펴보는게 답이겠지만, 위와 같은 방식을 사용해보니 코드의 흐름을 보다 빠르게 파악하고, 코드를 왜 이렇게 짰는지를 이해하기 편했습니다.

제가 작성한 내용은 지극히 저의 개인적인 생각이며, 입사한지 3주된 새내기의 생각이니 이에 대한 다양한 의견은 언제나 환영입니다 :)

**Comment by leejaeseung** [comment]
많은 의견 감사합니다!
저도 유지보수에 대해 팀 내에서 느꼈던 점을 정리해 봅니다.
- **정말 필요한 주석, 코드가 아니라면 그때그때 지우자!**
  - 나중에 코드를 볼 때 오해의 여지가 생길 수 있습니다. 해당 코드를 작성한 시점과 현재 시점의 정책이 다른데 주석은 이전 시점 기준으로 되어 있어 오해를 불러온 경우가 실제로 있었습니다.
- **테스트 코드는 비즈니스 로직을 이해하는 창이다.** (정말 중요하다고 생각합니다.)
  - 비즈니스 로직을 하나의 클래스 내에서 이해하려 하면, 여러 클래스를 타고 타고 또 타고 내려가며 이해하는 경우가 대부분입니다. 상당히 복잡한 작업인데, 이 때 잘 정돈된 테스트 코드를 본다면 어떤 비즈니스 로직을 가지는지 한 눈에 확인할 수 있습니다.
  - 테스트 케이스의 제목을 잘 지어야 한다고 생각합니다. (각 케이스를 특성 별로 잘 쪼개면 더욱 좋습니다.) 테스트 코드도 결국 코드이기 때문에 코드만 놓고 본다면 결국 비즈니스 로직 코드를 보는 것과 비슷한 노력이 듭니다.
  해당 테스트 케이스의 동작을 잘 설명한 제목이라면 코드를 한 줄도 읽지 않고 비즈니스 로직을 이해할 수 있습니다.

**Comment by wooyounggggg** [comment]
프로젝트 이해에 필요한 task의 목록은 앞선 의견들과 동일하므로, 가졌던 마음가짐이나 노력 측면에서 이야기 해보겠습니다.

프로젝트에 투입 되었을 때, 방대한 양의 코드에 이해가 어려웠습니다. 기술이나 구조 관련 스펙이 존재한다 할지라도, 배경 지식이 없으니 잘 읽히지도 않았구요. 또 빨리 프로젝트를 이해해서 아웃풋을 내고 싶다는 생각에 마음을 급하게 먹은 부분도 프로젝트를 이해에 방해가 되었습니다.

여러 시행착오를 거치면서 이러한 문제들을 또 겪지 않기 위한 나름의 원칙들을 세웠는데, 그 내용은 아래와 같습니다.

### 프로젝트를 내 언어로 재정의 해야한다.
일정 규모 이상의 프로젝트에는 프로젝트를 설명하는 많은 문서가 존재합니다. 문서를 보면 이해가 어렵지 않은 당연한 내용들이기 때문에 빠르게 이해하면서 읽어 나가지만, 읽을 때는 당연했던 지식의 양이 늘어나면서 어느 순간 정보들이 뒤섞이고 머리 속에 정리해 둔 지식들이 무너지기 시작합니다.

이러한 일의 원인은 다른 사람의 언어로 정의되어 있는 지식을 별도의 정제 과정 없이 받아들이고, 이해했다고 착각하기 때문인 것 같습니다.
읽었던 정보를 머리속에 구조화해서 정리하지 않았으니, 당연히 이를 재생산하는 것에도 한계가 있을 수 밖에 없습니다.

남의 언어로 정리되어 있는 정보를 스스로의 언어로 정리하는 과정에서는 그것들을 해체하고 재조립하는 과정이 필히 수반되기 때문에, 단순 글을 읽어 내려가는 것보다 훨씬 촘촘한 지식 체계를 구축할 수 있다고 생각합니다.

저도, 이러한 방법을 적용하여 프로젝트의 이해에 큰 도움이 되었습니다.

### 지름길은 없다.
저는 초기에 마음을 급하게 먹다보니, 무조건 빨리 프로젝트를 이해하려고 했던 것 같습니다.
하지만 그렇게 하면 할수록 점점 이해가 어려워지는 느낌이 들었고, 다행히 예전에도 비슷한 경험이 있어 최대한 마음을 느긋하게 먹고
천천히 일을 진행하니 훨씬 수월하게 상황을 해결할 수 있었습니다.

우리가 투입된 프로젝트는 구성원들이 오랜 시간을 투자한 결과물이기 때문에, 일정량의 시간 투자는 필연적인 것 같습니다.

### 기억보단 기록
이 또한 앞선 얘기들과 비슷한데, 하나라도 빨리 하고 싶은 마음에 내가 이해한 것들을 적어두는 시간 투자가 아깝다는 생각이 들었고
기억에 의존해서 이해하려 시도했던 적이 있었습니다.

그러나 이것도 시간이 지날수록 점점 비효율을 낳는 것을 체감할 수 있었고, 최대한 기록하려고 노력했습니다(저는 특히 볼펜과 종이에 기록했습니다). 그렇게 하니, 기록이 많아지면 많아질 수록 점점 효율이 증가하는 것을 느낄 수 있었던 것 같네요.

**Comment by leejaeseung** [comment]
신입 개발자가 물어보면서 5일만에 pr 올리기 vs 그냥 자기 생각대로 2일만에 pr 올리기
아니다 싶으면 물어보자(사회생활을 관통하는)
모아두면서 질문하기
