### ISSUE TITLE
[additional] Movie - 생성자와 정적 팩토리 메서드

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#6]
## 연관 챕터
#3 

## 조사 내용
책에선 Movie 에 AmountDiscountPolicy 나 PercentDiscountPolicy 가 적용됨을 생성자에 파라미터로 전달된 객체로 알 수 있습니다.
하지만 생성자에 파라미터로 Policy 를 넘겨주게 되면, 파라미터가 적을 땐 이해할 순 있어도 파라미터가 많아지면 어떤 Movie 에 어느 Policy 가 적용되었는지 파악하기 힘들 수 있습니다.
    
Movie 생성자를 사용하는 대신, 생성자를 사용하지 않고, 정적 팩토리 메서드를 사용하면 Movie 를 생성할 때 더 명확하게 Movie 의 Policy 를 지정해줄 수 있습니다.
    
ex)
    
```java
public class Movie {
    //...
    private DiscountPolicy discountPolicy;

    private Movie(..., DiscountPolicy discountPolicy) {
    	//...
        this.discountPolicy = discountPolicy;
    }

    public static Movie AmountDiscountMovie(...) {
    	//...
        return new Movie(..., new AmountDiscountPolicy());
    }

    public static Movie PercentDiscountMovie(...) {
        //...
        return new Movie(..., new PercentDiscountPolicy());
    }
}

Movie movie = new AmountDiscountMovie(...);
```
    
위처럼 정적 팩토리 메서드를 사용하면 생성된 Movie 에 어떤 정책이 적용되었는지 단지 메소드명만으로 알 수 있습니다.
그리고 메소드명 만으로 Policy 를 적용할 수 있기 때문에 이후에 Movie 객체를 생성할 때 어떤 Policy 를 적용할 수 있는지 한 눈에 확인할 수 있어 생산성이 올라갑니다.

**Comment by wooyounggggg** [comment]
좋은 의견인 것 같습니다. 저는 추가적으로, `Movie 클래스는 어떻게 추상화 해야하지?`라는 의문을 갖고 접근해보았습니다.

주어진 코드대로라면, Movie 클래스를 사용하는 클라이언트 시점에서 보았을 때는 컴파일 타임에 어떤 정책을 적용해야 할 지 구체적으로 알게 되고, 이는 아래의 예시처럼 객체 사이에 강한 결합을 유도하는 방향으로 코드가 흘러갈 가능성이 있지 않을까 생각했습니다.

```java
public class MovieClient {

    private Movie movie;
    
    public MovieClient() {
        movie = Movie.AmountDiscountMovie(...);
    }
}
```

위와 같은 코드가 있을 때,
AmountDiscount Policy를 사용하던 `MovieClient`가 모종의 이유로 생성자 호출 시점에 다른  Policy를 가진 Movie 객체를 필요로 하게 된다면, `Movie.PercentDiscountMovie(...)`를 호출해야 하고, 이는 곧 코드의 변경을 의미합니다.

그래서, Movie라는 도메인의 할인 정책이 시시각각 바뀔 수 있는 속성을 가진다면 Movie를 생성하는 Factory 클래스를 중간에 끼워넣어 객체 생성을 추상화 할 수 있을 것 같습니다.

```java
public class MovieFactory {

    public static Movie of(...) {
        if(...) {
            return new Movie.AmountDiscountMovie(...);
        } else if(...) {
            return new Movie.PercentDiscountMovie(...);
        } else if ...
    }

}

public class MovieClient {

    private Movie movie;
    
    public MovieClient() {
        movie = MovieFactory.of(...);
    }

}
```

또한 이렇게 객체의 생성 책임을 MovieFactory에 부여하다 보니, 기존에 Movie 클래스에 존재하던 정적 팩토리 메서드를 MovieFactory로 옮기는 것이 더 책임을 올바르게 분리한 것이 아닐까 하여, 아래와 같이 구체적인 정책 결정 요소도 MovieFactory로 옮겨주었습니다.

```java
public class MovieFactory {

    public static Movie of(...) {
        if(...) {
            return new Movie.AmountDiscountMovie(...);
        } else if(...) {
            return new Movie.PercentDiscountMovie(...);
        } else if ...
    }
    
    private static Movie AmountDiscountMovie(...) {
        ...
    }

    private static Movie PercentDiscountMovie(...) {
        ...
    }

}
```

Movie 클래스의 추상화 관점에서 이러한 시도를 해보았는데, 또 다른 의견이 있으시다면 제시해주시면 좋을 것 같네요 :)

**Comment by leejaeseung** [comment]
###내용 정리
- Movie 클래스를 추상화하려 할 때, Movie 의 생성 코드가 MovieClient 내부로 들어가기 때문에 정적 팩토리 메서드로 얻는 가독성 증가라는 이득이 사라진다.
- Movie 내부에 DiscountPolicy 마다 생성 메소드를 만들기 때문에 DiscountPolicy 의 정책이 늘어날 때마다 메소드도 추가해 줘야 한다. -> 상위 객체의 변화에 의존한다.

생각지 못했던 부분들을 많이 짚어주셔서 살짝 놀랐네요! ㅋㅋ 의견주신 내용들을 참고해서 더 좋은 방법은 없을지 고민해봐야겠네요

**Comment by binchoo** [comment]
어제 패키징 관련하여 말로 설명드린 내용을 글로 보충하겠습니다!

책에서 패키지 구조에 대해서는 등장하지 않았습니다만,
만약 아래 그림과 같은 구조를 갖는다고 가정하겠습니다.

![image](https://user-images.githubusercontent.com/15683098/160311066-d8ae3b83-79b5-425d-adc2-bf22c63bc5ca.png)

그림에서 패키지는 3가지가 존재합니다.
`package movie`
`package movie.conditions`
`package movie.policies`



상위 정책들은 `movie` 패키지에 담습니다. 
구체적인 정책들은 하위 패키지에 담습니다.


우리가 소스코드를 작성할 때, 하위 정책 코드가 상위 정책 소스코드를 의존하도록 하는 것과 마찬가지입니다.

하위 패키지 폴더가 상위 패키지 폴더에 의존하게 만들어서
상위 패키지는 하위 패키지로부터 독립하게 됩니다.

이런 구조를 갖게 되면
클라이언트 프로그램을 `movie` 패키지만 임포트하여 아무 오류 없이 컴파일 할 수 있습니다.

런타임에서 실행될 클라이언트 프로그램이 필요하다면,
비로소 `movie.conditions`와 `movie.policies` 패키지를 임포트하고 구체적인 객체들을 DI 해주면 됩니다.

---
하지만, 아래 예시와 같이 상위 소스코드가 하위 소스코드를 의존할 경우
`movie` 패키지는 단독으로 배포될 수 없습니다. 반드시 하위 패키지 `movie.conditions`, `movie.policies`를 함께 배포해야 합니다.

```
package movie;

/**
* 소스코드 의존성이란 import 문을 보면 바로 파악할 수 있습니다. 
* Movie 클래스가 하위 클래스들에 의존하였고, 결국 상위 패키지가 하위 패키지에 의존하는 모습입니다.
*/
import movie.conditions.*; 
import movie.policies.*; 

public class Movie {

   ...
    public static Movie AmountDiscountMovie(...) {
    	//...
        return new Movie(..., new AmountDiscountPolicy());
    }

    public static Movie PercentDiscountMovie(...) {
        //...
        return new Movie(..., new PercentDiscountPolicy());
    }
}
```

**Comment by wooyounggggg** [comment]
정적 팩토리 관련해서 백기선님의 영상도 올라온 게 있어 공유합니다
https://www.youtube.com/watch?v=P-HQ9ab9fc0

**Comment by leejaeseung** [comment]
확실히 의존적인 속성을 정적 팩토리로 관리하면 구조가 많이 꼬이게 되겠네요. 그 부분까진 미처 생각 못했는데 정리해 주셔서 감사합니다!
https://velog.io/@ljinsk3/%EC%A0%95%EC%A0%81-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C%EB%8A%94-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%A0%EA%B9%8C

다른 글을 찾아보니 정적 팩토리 메서드는 완전히 독립적인 속성을 변경하는 생성자나 캐싱, 하위 객체에 대해서 사용하는게 가장 적절하겠네요.
많이 배워갑니다! :)
