### ISSUE TITLE
[chapter] 3장 - 역할, 책임, 협력

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#7]
## 제목
3장 - 역할, 책임, 협력

**Comment by leejaeseung** [comment]
예전부터 코드를 짜면서 궁금한 부분이 있었는데, 여러 의견을 들어보고 싶습니다~!

질문.
```
한 클래스에서 비즈니스 로직을 짜는데 코드가 너무 길어져 가독성을 위해 여러 개의 private 메소드로 분리했다. 즉, 1개의 public 메서드, 3개의 private 메서드가 생겼다고 치자.
테스트코드를 짤 때, 결국 4개의 메소드가 하나의 비즈니스 로직이므로 통으로 단위 테스트코드를 짜야 한다. 메소드 단위로 테스트코드를 분리하면 더 깔끔하긴 하겠지만 private 메서드를 테스트하는 건 뭔가 좀 그렇다.

1. 그냥 public 메서드에 대해 통으로 짠다. 하나의 비즈니스 로직이니까!
2. 모두 public 메서드로 바꾸고 각각 테스트한다. but 다른데서 쓰이지 않는 메서드가 public이 됨.
3. 책임을 나눠서 새로운 클래스를 만들어 private 메서드를 다른 클래스의 public 메서드로 옮긴다. but 하나의 메서드만 가진 클래스만 많이 생긴다면..? 클래스가 많아져 오히려 복잡해지지 않을까?
4. private 메소드도 우회해서 테스트하자!
```

**Comment by emiling** [comment]
이 논쟁과 관련하여 다른 소프트웨어 개발자분들의 의견을 공유합니다.

- Kent Beck (https://twitter.com/KentBeck/status/1258954349314625538)

<img width="601" alt="스크린샷 2022-04-03 오후 2 11 02" src="https://user-images.githubusercontent.com/30731518/161412621-11f565e5-defa-4ac4-85b7-d274838d0816.png">


http://shoulditestprivatemethods.com/

``` html
<!-- Every time you consider testing a private method, your code is telling you that you haven't allocated responsibilities well.  Are you listening to it? -->
```

- 비공개 메서드를 테스트 해야하는가? (https://justhackem.wordpress.com/2017/09/29/should-private-methods-be-tested)

> 공개 메서드의 인터페이스는 테스트 하지 않지만 비공개 메서드의 구현은 테스트 대상이다.
