### ISSUE TITLE
[keyword] 3장 - 역할, 책임, 협력

### ISSUE THREAD

**Issue by wooyounggggg** [caffeine-library/objects#8]
## 주제

`3장 - 역할, 책임, 협력`을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#7

**Comment by binchoo** [comment]
이 챕터는 협력/책임/역할/객체/상태에 관하여 소개합니다.
협력, 책임, 역할을 설계하지 않은채 구현부터 시작하지 말도록 권고하고 있으며, 
이 개념들을 설계에서 어떤 순서로 정립해야 하는지도 가이드하고 있습니다.

## 용어 정리

### 협력
응용의 기능을 구현하기 위한 객체들의 상호작용 컨텍스트를 지칭한다.

#### 협력의 수단
- 메시지 전송
한 객체는 협력자 객체에게 요청한다
- 메서드 실행
메시지에 대한 응답으로 협력자 객체는 메서드를 실행한다.

### 책임
협력의 컨텍스트가 마련되었을 때 각 역할이 수행해야하는 것. 
- 해야 할 책임
- 알아야 할 책임

#### 책임의 할당
전문가 패턴
- 책임을 수행하는 데 필요한 정보를 가장 잘 알고 있는 전문가에게 책임을 배정한다.
ex) 영화 예매의 대상이 상영이고 상영시간과 상영요금에대해 잘 알고 있다, 따라서 상영이 영화 예매를 책임진다.

### 역할
협력의 컨텍스트 안에서 객체가 수행하는 책임의 집합.
책임을 먼저 식별한 뒤 이들을 역할(객체)에게 배정하면 된다.

#### 역할과 객체
- 역할은 슬롯과 같다. 서로 다른 방식으로 책임을 실현 가능하다면 역할을 배정한다.
- 오직 한가지 방식으로 책임을 실현한다면 객체를 배정한다.
- 처음엔 객체로 시작하고, 서로 다른 방식이 책임을 수행할 수 있게되면 그 때 역할을 도입해도 늦지 않는다.

#### 역할의 선결 조건: 메시지
역할이 수신하게 될 메시지를 먼저 정의한다. 
- Top-down 방향으로 설계하므로 최소한의 인터페이스만 식별할 수 있다. 
- 클라이언트가 원하는 What에 집중한다. 구현에 관한 How에는 관심이 없으므로 추상적으로 인터페이스를 정의하게 된다.

#### 상태의 선결 조건: 행동
상태는 단지 객체가 행동을 잘 수행하기 위해 필요한 재료이다.

## 설계의 순서
응용의 **기능**> 어떤 **협력**이 필요할까?> 어떤 **책임**이 필요할까? 분할된 책임이 무엇일까?> 어떤 **메시지**가 필요할까?> 어떤 **역할/객체**에게 책임을 할당할까?> 어떤 **행동**이 필요할까?>어떤 **상태**가 필요할까?

```
기능: 영화 예매>
컨텍스트: 객체들이 상호작용하여 영화 예매를 성공적으로 달성하기
책임: 영화를 예매하기, 영화 가격을 계산하기, 영화 가격 계산시 할인가격을 차감하기, ...
메시지: reserve, getAmount, getDiscountAmount ...
역할(객체): Screening, Movie, DiscountPolicy, DiscountCondition ...
행동: 최소한의, 추상적인, 자율적인 인터페이스
상태: Screening은 상영하는 Movie를 알아야 한다, Movie는 기본 가격과 DiscountPolicy를 알아야 한다 ...
```
